# Generated by Django 6.0.1 on 2026-02-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_unique_user_post_comment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_user_post_comment',
        ),
    ]
